### ISSUE TITLE
[02.todo] checkbox doesn't work correctly

### ISSUE THREAD

**Issue by xuzheng465** [PacktPublishing/Building-Real-world-Web-Applications-with-Vue.js-3#46]
I have to refresh the page to check or uncheck the checkbox.

**Comment by raduchiriac** [comment]
@xuzheng465 inside the `ListItem.vue` add this under `<style scoped>`
```css
input {
  pointer-events: none;
}
```
